server:
 port: 8060
 
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
 

spring:
  application:
    name: api-gateway 
  cloud:
    gateway:
      routes:
      - id:  products
        uri: lb://productsApi  
        predicates:
         - Path=/products/**
        filters:
          - AuthenticationFilter
        
      - id:  order
        uri: lb://orderitemApi
        predicates:
         - Path=/order/**
        filters:
          - AuthenticationFilter
            
      - id:  identity-service
        uri: lb://identity-service
        predicates:
         - Path=/auth/** 
        filters:
          - AuthenticationFilter      
        
