server:
 port: 8666


spring:
 datasource:
  url: jdbc:mysql://localhost:3306/mydb
  username: root
  password: root
 jpa:
  hibernate:
   ddl-auto: update
   show-sql: true
 application:
  name: orderitemApi   
   
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/      


 
